site_name: MyAIweb
nav:
- Home: index.md
- Paper Notes:
    - 2D: Paper_Notes/2D_List.md
    - 3D: 
        - 3D Occupancy: Paper_Notes/3D/3D_Occ_List.md
- Server Tips:
    - screen: Server_Tips/screen.md
- Github Tips: Github_Tips/upload.md
- System Tips:
    - Ubuntu: 
        - Hardware: System_Tips/Ubuntu/Hardware.md
        - Command: System_Tips/Ubuntu/Command.md
- DL Skills: DL_Skills/Skills.md

theme:
    name: material

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js